### ISSUE TITLE
run a typescript file directly without transpiling

### ISSUE THREAD

**Issue by rhyek** [reactiverse/es4x#107]
I've set a TS file as my main file in the package.json, but wen running `npm start` it throws the following error:
```
ModuleError: Module "./src/app.ts" was not found
```

**Comment by pmlopes** [comment]
GraalJS and ES4X do not run TypeScript directly, the engine is pure ES2019, which means it still needs a compilation step. You can use something like:

`tsconfig.json`:
```json
{
  "compilerOptions": {
    "outDir": "dist",
    "sourceMap": true,
    "noImplicitAny": true,
    "module": "commonjs",
    "target": "es5",
    "allowJs": true
  }
}
``` 

`package.json`:

```json
{
  "name": "my-tsproject",
  "main": "dist/index.js",

  "scripts": {
    "prestart": "tsc",
    "start": "my-tsproject"
  },

  "devDependencies": {
    "typescript": "^3.2.2",
  }
}
```

So when you run your application using the build tool, it precompiles your TS to JS and then invokes the normal application.

**Comment by rhyek** [comment]
thanks.
