### ISSUE TITLE
typescript throw errror

### ISSUE THREAD

**Issue by daihy8759** [reactiverse/es4x#117]
package dependencies is
```
    "dependencies": {
        "@vertx/core": "^3.7.1",
        "@vertx/redis-client": "^3.5.4",
        "@vertx/web": "^3.7.1"
    },
    "devDependencies": {
        "@vertx/unit": "^3.7.1",
        "typescript": "^3.5.2"
    }
```

```
node_modules/@vertx/bridge-common/index.d.ts:25:3 - error TS2416: Property 'complete' in type 'BaseBridgeEvent' is not assignable to the same property in base type 'Future<boolean>'.
  Type '(arg0: boolean) => void' is not assignable to type '{ (result: boolean): void; (): void; }'.

25   complete(arg0: boolean) : void;
     ~~~~~~~~

node_modules/@vertx/bridge-common/index.d.ts:27:3 - error TS2416: Property 'tryComplete' in type 'BaseBridgeEvent' is not assignable to the same property in base type 'Future<boolean>'.
  Type '(arg0: boolean) => boolean' is not assignable to type '{ (result: boolean): boolean; (): boolean; }'.

27   tryComplete(arg0: boolean) : boolean;
```

**Comment by pmlopes** [comment]
@daihy8759 could you provide a simple snippet that shows the error? I've looked at the `.d.ts` and it doesn't seem to be any issue with the definition file so it should be something about it's usage i guess...

**Comment by daihy8759** [comment]
thanks ,i provide example project [es4x-example](https://github.com/daihy8759/es4x-example)

**Comment by pmlopes** [comment]
The latest typescript compiler is more strict than it used to be, the codegen module has been updates to mark all import failures as non errors (the reason is that a module might require another optional module) and if it's not present (which is fine) at runtime will cause the compiler to assert an error at parsing of the type definition.

This will be available once all modules get rebuilt (when vert.x 3.8.0 comes out).

**Comment by pmlopes** [comment]
The second issue with the type mismatch has been also fixed with a override

**Comment by pmlopes** [comment]
Fixed by: https://github.com/reactiverse/es4x/commit/6fe29202d789b50dfadc66a1c9b1ea89a4bfe47c

**Comment by daihy8759** [comment]
3.8.0 still have compile problem.
```
[I] ➜ yarn start
yarn run v1.17.3
$ tsc
node_modules/@vertx/web/options.d.ts:17:10 - error TS2440: Import declaration conflicts with local declaration of 'PermittedOptions'.

17 import { PermittedOptions } from '@vertx/bridge-common/options';
            ~~~~~~~~~~~~~~~~


Found 1 error.
```

**Comment by pmlopes** [comment]
I am aware of this, this will be fixed when we upgrade to vertx 4 (the class name colision dissapears) but i also noted that if you ignore the error the compiler does generate working code.

```
tsc || true
```

This shouldn't be done but if it's blocking you you can try it...

**Comment by Asfolny** [comment]
Fun fact, true isn't recognized on windows;
```
tsc || exit 0
```
But it'll be fixed soon™
