### ISSUE TITLE
Is es4x npm install broken on Windows?

### ISSUE THREAD

**Issue by pvider** [reactiverse/es4x#135]
OS: Windows 10
I got:
![image](https://user-images.githubusercontent.com/33367771/61791916-05bf7580-ae24-11e9-8b2e-49a792253e93.png)
Content of `es4x.cmd` inside `npm` directory:
```
@IF EXIST "%~dp0\bash.exe" (
  "%~dp0\bash.exe"  "%~dp0\node_modules\es4x-pm\bin\es4x" %*
) ELSE (
  @SETLOCAL
  @SET PATHEXT=%PATHEXT:;.JS;=;%
  bash  "%~dp0\node_modules\es4x-pm\bin\es4x" %*
)
```
Is using `bash` command good practice for 'global' npm packages?
Looking at other npm packages like `pm2`, they launch js-scripts using `node`:
```
  node  "%~dp0\node_modules\pm2\bin\pm2" %*
```
As a workaround currently I copy content of `npm/node_modules/es4x-pm/bin` into `npm` to make it work.

**Comment by pmlopes** [comment]
This is a packaging issue as the install script should not use bash at all

**Comment by pmlopes** [comment]
Npm will create the cmd shim instead of using the provided one. The fix means we should provide the script as a node script so on Windows it will also work.
