### ISSUE TITLE
Possible error in esx4-launcher.cmd on Windows 10

### ISSUE THREAD

**Issue by pvider** [reactiverse/es4x#136]
OS: Windows 10
Cannot launch example project.
![image](https://user-images.githubusercontent.com/33367771/61803547-03b4e100-ae3b-11e9-9cfb-3a1cae31f7d9.png)
I am trying to follow this guides: https://reactiverse.io/es4x/start/install/ and https://reactiverse.io/es4x/start/hello-world/
The content of `esx4-launcher.cmd` in `node_modules/.bin` folder is
```
@ECHO OFF

SETLOCAL

SET "JAVA_EXE=%JAVA_HOME%\bin\java.exe"
IF NOT EXIST "%JAVA_EXE%" (
  SET "JAVA_EXE=java"
)

IF EXIST "%~dp0\..\.jvmci" (
  SET "JVMCI=--module-path=%~dp0\..\.jvmci -XX:+UnlockExperimentalVMOptions -XX:+EnableJVMCI --upgrade-module-path=%~dp0\..\.jvmci\compiler.jar"
)

"%JAVA_EXE%" -XX:+IgnoreUnrecognizedVMOptions "%JVMCI%" "%JAVA_OPTS%" -jar "%~dp0\es4x-launcher.jar" %*
```

If I comment `@ECHO OFF` with `REM` then I get this log:
```
C:\Test\es4x-test>REM @ECHO OFF
C:\Test\es4x-test>SETLOCAL
C:\Test\es4x-test>SET "JAVA_EXE=C:\Programs\graalvm-ce\bin\java.exe"
C:\Test\es4x-test>IF NOT EXIST "C:\Programs\graalvm-ce\bin\java.exe" (SET "JAVA_EXE=java" )
C:\Test\es4x-test>IF EXIST "C:\Test\es4x-test\node_modules\.bin\\..\.jvmci" (SET "JVMCI=--module-path=C:\Test\es4x-test\node_modules\.bin\\..\.jvmci -XX:+UnlockExperimentalVMOptions -XX:+EnableJVMCI --upgrade-module-path=C:\Test\es4x-test\node_modules\.bin\\..\.jvmci\compiler.jar" )
C:\Test\es4x-test>"C:\Programs\graalvm-ce\bin\java.exe" -XX:+IgnoreUnrecognizedVMOptions "" "" -jar "C:\Test\es4x-test\node_modules\.bin\\es4x-launcher.jar"
Error: Could not find or load main class
```

When I am trying to launch `C:\Programs\graalvm-ce\bin\java.exe -XX:+IgnoreUnrecognizedVMOptions "" "" -jar "C:\Test\es4x-test\node_modules\.bin\\es4x-launcher.jar"` I get same error:
`Could not find or load main class`

This is incorrect arguments: `"" ""`
If I remove them then my project launches.

So as a workaround I currently fixed last line of `esx4-launcher.cmd` in `node_modules/.bin` folder:
```
"%JAVA_EXE%" -XX:+IgnoreUnrecognizedVMOptions -jar "%~dp0\es4x-launcher.jar" %*
```
Otherwise it doesn't start.

**Comment by pmlopes** [comment]
Perhaps removing the quotes will also fix it?

```
"%JAVA_EXE%" -XX:+IgnoreUnrecognizedVMOptions %JVMCI% %JAVA_OPTS% -jar "%~dp0\es4x-launcher.jar" %*
```

**Comment by pvider** [comment]
@pmlopes yes, removing the quotes also fixes it.

**Comment by pmlopes** [comment]
Quick win patch install command to not quote the two variables.

**Comment by nintha** [comment]
@pmlopes  `yarnpkg create vertx-app` has same problem. 

I try to fix it by removing quote on `%JVMCI%` and  `%JAVA_OPTS%` in file `\node_modules\.bin\<project name>.cmd` manually.
