### ISSUE TITLE
Add support for installing offline

### ISSUE THREAD

**Issue by UglyHobbitFeet** [reactiverse/es4x#143]
I am on a machine that has a local maven repo. It is completely offline from the rest of the world.

I am doing an npm install. during that it runs the 'es4x install' command.  It fails with the error:

    Cannot resolve artifacts [io.vertx:vertx-web-common:3.7.1, (and more omitted) 
    Failed to read artifact descriptor for io.reactiverse:es4x.jar:0.8.0
      at io.reactiverse.es4x.commands.Resolver.resolve(Resolver.java.178)

If I crack open the source code for Resolver, I see a hard coded string for 

    DEFAULT_MAVEN_REMOTE="https://repo1.maven.org/maven2"

Is there a way to have a user override this by passing something in, or modifying a property file, etc? Any kind of workaround I can do?

**Comment by UglyHobbitFeet** [comment]
I will just copy the mentioned files into my own .m2 repo and assume it will pick them up.

**Comment by pmlopes** [comment]
I'd assume that if all dependencies are in `~/.m2/repository` then it should be OK if there's no reference to snapshots
