### ISSUE TITLE
Polyglot support

### ISSUE THREAD

**Issue by sj82516** [reactiverse/es4x#146]
How can I use Polyglot in my project ?   
Here is my sample code.    

```
/// <reference types="@vertx/core/runtime" />
// @ts-check

Polyglot.evalFile("R", "functionGraph.r");
var plotFunction = Polyglot.import('plotFunction');

vertx
    .createHttpServer()
    .....
```

The error message is "Polyglot is undefined" but my process.engine is graal.js

**Comment by pmlopes** [comment]
A couple of things here. The context used in es4x isn't enabling polyglot access (which should be configurable) and don't forget to install R in your graal installation. 

Also note that R will then only work on graalvm not in openjdk >=11 mode.

**Comment by pmlopes** [comment]
The polyglot support should be configurable but disabled by default so it will work with all jdks by default.

Add a `--polyglot` flag to the launcher to enable it.

**Comment by sj82516** [comment]
I check `gu list` and R is installed.  
I run `./node_modules/.bin/es4x-launcher --polyglot` still not work.
Should I wait for 0.9.0 ?

**Comment by pmlopes** [comment]
This enabling isn't implement yet I just described what needs to be done 😁

**Comment by sj82516** [comment]
Oh I see.   
Looking forward this feature.

**Comment by pmlopes** [comment]
It should be simple so I might be able to implement it this week and release after that 🤞
