### ISSUE TITLE
Question: how to debug with debugger?

### ISSUE THREAD

**Issue by rquast** [reactiverse/es4x#19]
All working well now, except for debugger. I tried to get the debugger to work with IntelliJ on port 9797 but IntelliJ would only show decompiled byte code. Have you managed to get the debugger to work, and was that on vscode or something?

**Comment by rquast** [comment]
May be related: https://github.com/Microsoft/vscode-java-debug/issues/152

**Comment by rquast** [comment]
![screenshot from 2018-06-28 15-51-37](https://user-images.githubusercontent.com/1103891/42015556-37715c8c-7aeb-11e8-80c4-2c3f28f7d62c.png)
It works with netbeans, but not vscode or intellij for me.

**Comment by pmlopes** [comment]
@rquast There is an issue while debugging from maven itself, this works for me:

* Package the application
* Start the debugger from the jat far

```
npm run package
java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=9797 -jar target/empty-project-1.0.0-fat.jar run ./index.js
```

![screenshot from 2018-06-29 15-21-03](https://user-images.githubusercontent.com/849467/42094433-16c3e78c-7bb0-11e8-9068-5e432805d8fb.png)

**Comment by rquast** [comment]
I tried it but it doesn't work for me. I figured it must be since I only have IntelliJ community edition. You need the ultimate edition for JS support.

Great to hear about the chrome support for GraalVM. Live debugging of node on chrome is a really powerful feature and it would be great to see something similar with this one day.

**Comment by pmlopes** [comment]
I was playing with Graal debugging using Chrome devtools and I had to fix some things but it works. It currently has some issue preventing using it from vscode but I've open an issue at graal side.
