### ISSUE TITLE
es4x init missing

### ISSUE THREAD

**Issue by UglyHobbitFeet** [reactiverse/es4x#193]
I have es4x-pm 0.8.0 which has es4x init.  When I upgrade to the latest, that command is gone. What is the equivalent?  I don't see any changes mentioned in the docs and they still mention to use it

**Comment by pmlopes** [comment]
Yes there is a bug with the script that has just been fixed on master

**Comment by pmlopes** [comment]
Expect a new release this week.

**Comment by UglyHobbitFeet** [comment]
ok, thanks!
