### ISSUE TITLE
es4x offline

### ISSUE THREAD

**Issue by UglyHobbitFeet** [reactiverse/es4x#194]
I have an offline project which has es4x-pm.

When I go into my project I do:

```
    npm install -g es4x-pm
    es4x init
    npm install @vertx/unit --save-dev
    npm install @vertx/core --save-prod
    npm install @vertx/web --save-prod
    npm install

```
During the npm install phase it kicks off an es4x install command.  That errors out with 'Could not transfer artifact io.vertx:vertx-&lt;somePackages> from/to central"...'UnknownHostException: repo1.maven.org'

How do I pass in a separate repo, or point the es4x install to the existing jars/poms on my local machine?

**Comment by UglyHobbitFeet** [comment]
Actually t looks like my local m2 has empty folders for these. I'm guessing it's a manual import on my end

**Comment by pmlopes** [comment]
I think that if you pass `-Dmaven.registry="https://repo1.maven.org/maven2/"` it should work. If not let me know so it can be fixed.

**Comment by pmlopes** [comment]
This needs to be documented.

**Comment by UglyHobbitFeet** [comment]
Manually adding the deps (and their dependencies) to my m2 repo worked for me. It will still be good to have your solution in the docs though!

**Comment by pmlopes** [comment]
@UglyHobbitFeet how do you install npm dependencies in this case? Are you using:

```
npm install --offline
```

If that's the case I can detect that by looking up the env var:

```
npm_config_offline
```

and disable online maven resolution too.

**Comment by UglyHobbitFeet** [comment]
I may have a unique case. I am using a mirror of npm that can be x days
old. The mirror is disconnected from the internet so it's considered
offline.
If I want maven repo stuff I can also point to a mirror that is x days old,
or I can physically move it from one network to the disconnected network

**Comment by pmlopes** [comment]
OK so you're not 100% offline, as your npm/yarn connects to this mirror, so yes it can be solved the way described above, either use a local maven cache or point to the mirror with the flag. I'm updating the flag to also consider a ENV var as it's easier to use e.g.:

```bash
MAVEN_REGISTRY="https://repo1.maven.org/maven2/" npm install
```

**Comment by UglyHobbitFeet** [comment]
I should clarify that the mirror is disconnected.  In other words, NPM
commands work but since the mirror can be x days old, I may not grab the
latest packages. If the packages try to reference the internet I will get
errors since the offline machines cannot access those urls.

**Comment by pmlopes** [comment]
ah ok, so it uses the local cache, which is the same as the `--offline` flag on npm. Ok so I can check the environment if the flag was used or part of the `npm/yarn` command and in that case disable the internet registry and only look on the local maven cache `~/.m2/repository`

**Comment by UglyHobbitFeet** [comment]
Awesome, thanks!

I also have one more thing and was wondering your thoughts on if I should
open a ticket for it.  Whenever I bring the vertx-web-graphql.jar onto a
disconnected machine I have to modify the graphiql.html file inside it
because the link and script references point to https links which are not
available to me.  I usually copy those referenced files into the jar and
change the link and script tags to point to them.

**Comment by pmlopes** [comment]
That should be reported upstream as the jar can be used by any language it's not es4x specific.

**Comment by UglyHobbitFeet** [comment]
will do, thanks!
