### ISSUE TITLE
CLI does nothing?

### ISSUE THREAD

**Issue by ImVexed** [reactiverse/es4x#199]
Little confused over here, after running `yarn global add es4x-pm`, `es4x init` does nothing, no output, no files changed, just silently closes. And so does every other command I try to give it.

Is this a regression or am I missing something?

**Comment by ImVexed** [comment]
Using version 0.9.1

**Comment by Asfolny** [comment]
I did actually run into this and forgot about it again..
If java isn't installed (or unreachable from the cmd) es4x doesn't throw any errors at all.

**Comment by pmlopes** [comment]
It requires graalvm to be on the path. There's an issue to let it also run on plain java but indeed it should do better logging if the missing parts aren't present
