### ISSUE TITLE
automate docs site deploy on commit to master

### ISSUE THREAD

**Issue by pmlopes** [reactiverse/es4x#204]
Docs are generated with vuepress. The way it works is by running the command:

```
npm run docs:build
npm docs: deploy
```

So on a successful build, the docs should be deployed.

This also requires that the generator project runs so type docs are also updated.

**Comment by Piyushhbhutoria** [comment]
please add more description, how to get started and what to look for?

**Comment by navyakanu** [comment]
@pmlopes , 
is this like adding a webhook in github which builds generator project first, then 
`npm run docs:build` 
`npm docs: deploy` 

- If yes, then how to build generator project?

I don't see any scripts in package.json for docs:deploy is it docs:publish?

**Comment by pmlopes** [comment]
Yes you're correct it's `publish`.

To build the type docs you also need maven installed and run:

```
cd generator
mvn -Pio.vertx,io.reactiverse clean generate-sources exec:exec@typedoc
```

One cool feature that could be another issue would be after codegen fake a install (say copy to a temp `node_modules` and run a full lint check for the generated type definitions to verify that all definitions are valid.

**Comment by pmlopes** [comment]
So the build order should be:

1. Run the generator
2. Build docs
3. Deploy

Maybe this could be a GitHub action to keep everything in one place?

**Comment by navyakanu** [comment]
Yes, Github actions will work, as they are in beta, I am not sure if you want to depend on it. Anyway, I tried github actions, but there is error, not sure if the steps are right

`mvn -Pcodegen install
        npm install verdaccio
        npm install typedoc
        cd generator
        mvn -Pio.vertx,io.reactiverse clean generate-sources exec:exec@typedoc
        cd ..
        npm run docs:build
        npm run docs:publish`

I think I have missed some steps, or not understanding the dependencies correctly
Error:
java.io.IOException: Cannot run program "typedoc" (in directory "/home/runner/work/es4x/es4x/generator/io.vertx/vertx-core"): error=2, No such file or directory

**Comment by pmlopes** [comment]
It should be:
```
npm install -g typedoc
cd generator
mvn -Pio.vertx,io.reactiverse clean generate-sources exec:exec@typedoc
cd ..
npm run docs:build
npm run docs:publish
```

The npm install should be global because it's assumed that `typedoc` is globally available. If that's an issue I think we can add it to the top level package json and make all references relative to the root installation... Or trigger it from npm which would put it on the path.
