### ISSUE TITLE
`vertxStart()` function is not called when deploying a verticle

### ISSUE THREAD

**Issue by jinsankim** [reactiverse/es4x#220]
Hi,
I've tried to deploy a verticle.

index.js
```
vertx.deployVerticle("my-verticle.js")
```

my-verticle.js

```
console.log("hello my-verticle");

exports.vertxStart = function () {
  console.log("This is my verticle and it is starting...");
}

exports.vertxStop = function() {
 console.info('stop called');
}
```

I've seen the log, "hello my-verticle", but couldn't see the log, "This is my verticle and it is starting...".

I expected `vertxStart()` function should be called. 

Is there anything that I misunderstood?

Thanks,

**Comment by pmlopes** [comment]
That is the old `vertx-lang-js` behavior. In es4x there's no start event as the moment, the script runs (when you see the first console log) is the start event.

You can however register a callback for the `undeploy` event with:

```js
process.on('undeploy', () => console.log('undeploying...'));
```

**Comment by jinsankim** [comment]
Thanks, that's enough information.

Please could you let me know where can I read the document that explains like what you described?

Thanks,

**Comment by jinsankim** [comment]
Got it.
If I have a chance to contribute to write some document, I'll try it.
Thanks for impressive project!
