### ISSUE TITLE
How to use `promisify` in `util.js`?

### ISSUE THREAD

**Issue by jinsankim** [reactiverse/es4x#224]
Hi, 

I have a personal project that is written with `node.js` and `typescript`. After finding this project, I'd like to migrate it to `es4x`! `es4x` is a little bit complicated for me to understand the concept but I'm trying.

When I tried to write some code w/ `es4x`, I've found that I want to use `async/await` not `callback`. I've found [your article](https://www.jetdrone.xyz/2017/01/24/Async-Await-Vertx.html) but it looks like out of date. And also I've found `promisify` function in [util.js](https://github.com/reactiverse/es4x/blob/develop/es4x/src/main/resources/node_modules/util.js) but I couldn't catch how to use it.

How to use `promisify` and `async/await` w/ `es4x`?

**Comment by pmlopes** [comment]
Hi @jinsankim, the article is indeed a bit outdated. es4x is now a `graaljs` only runtime which means async/await are supported out of the box. However the vert.x APIs are only going to be fully promise friendly in 4.0 (expect end of the year). Until then they need to be wrapped with the utility you found.

So the utility works pretty much like node: https://nodejs.org/api/util.html#util_util_promisify_original

given any callback based api, it will return a promise friendly alternative or given a vertx API it will return a wrapper for any call and assume the last argument is a callback.

Here's one example from the test:

```js
async function futureTest1 () {
  let server = await vertx
      .createHttpServer()
      .requestHandler(req => {
      })
      .listen(0);

  console.log('Server Ready!');
}

futureTest1()
  .then(function (result) {
    test.complete();
  })
  .catch(function (err) {
    should.fail(err)
  });
```

Be aware this is really new to graaljs and will be better once graal 19.3.0 is release + Vert.x 4.0 at that moment we can verify that it all works as expected without wrappers.

**Comment by jinsankim** [comment]
How can I import `util.js`?

**Comment by pmlopes** [comment]
pretty much like in node it's an internal module so:

```js
const util = require('util')
```

**Comment by pmlopes** [comment]
however, in `mjs` mode there's no require available... so this isn't possible... and an alternative approach needs to be found...

**Comment by jinsankim** [comment]
I'm writing code w/ `typescript` and it couldn't find `util` module. :(

**Comment by pmlopes** [comment]
Ah that's another issue, we need to add type definitions for those modules too.

**Comment by pmlopes** [comment]
type definitions for these modules have been added in `0.9.5`. I'll start working on the documentation next week. But in the meantime after a new `install` run and if you have:

```js
/// <reference types="es4x.d.ts" />
```

Then those module definitions should be visible. I'll be fixing the documentation and try to avoid this install step by moving the definition file to the `pm` package itself so it will be globally available on all projects.

**Comment by pmlopes** [comment]
0.10.0 includes `.d.ts` files for these modules.
