### ISSUE TITLE
proxy support

### ISSUE THREAD

**Issue by hc-codersatlas** [reactiverse/es4x#242]
Tried setting -Dhttp.proxyHost in JAVA_OPTS, MAVEN_OPTS etc, but it's not working. Is it possible to install the dependencies using a proxy?

Thanks.

**Comment by pmlopes** [comment]
Hi, I think the env var `MAVEN_REGISTRY` should do what you want. The pm package doesn't use maven underneath (just the resolver engine) so any maven specific config might not be available...

**Comment by hc-codersatlas** [comment]
Hi, I'm not looking to specify a custom maven registry so not sure if that helps. I'm referring to how the installer goes and downloads the required jars using Aether? and that doesn't support a http proxy. So in the instance where there's a firewall and proxy required it doesn't support it. Thanks.

**Comment by pmlopes** [comment]
@hc-codersatlas the scripts manually downloaded would support JAVA_OPTS, the npm one didn't (as it is implemented in js). This commit will support it:

https://github.com/reactiverse/es4x/commit/9437ed6b5c9cd89e933c33c1c8ef5d9818efbb80
