### ISSUE TITLE
Is there any way to get current jar directory in JavaScript ?

### ISSUE THREAD

**Issue by chengenzhao** [reactiverse/es4x#259]
Hi:

In Java, we could use 
`new File(Launcher.class.getProtectionDomain().getCodeSource().getLocation().toURI()).getParent();`
to get current path of jar file
and in node, __dirname could provide us the current directory path of the file
but if we pack es4x project into a fat jar
__dirname will return a relative path starting with "jar:"
so is there any way to get the current directory of jar file in JavaScript?

thx

**Comment by pmlopes** [comment]
Humm, that's tricky because the vertx filesystem is used to locate files so it considers all jars in the classpath.

You can however add a well known jar with the `vendor` flag and you know where they are.

For example see here:

https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/JavaScript/es4x/package.json#L26

**Comment by chengenzhao** [comment]
Thanks a lot
That should work but it still needs some script to parse in the path
and we check the source code of es4x
it seems like we could get current working directory by 
`VertxFileSystem.getCWD()`java
so is it possible to bind this cwd to the global?
```java
    // add cwd as a global
    bindings.putMember("cwd", VertxFileSystem.getCWD());
```
thus we could use this cwd binding for some file system operations
coz we will use current directory to store some data to make the whole system simple and easy to use:)

**Comment by chengenzhao** [comment]
Besides, is it possible for Vert.x File System to expose CWD?

**Comment by chengenzhao** [comment]
After checking the source code, we find out that we could use 
```javascript
const System = Java.type('java.lang.System');
var cwd = System.getProperty("user.dir", "");
```
to get the default cwd but it would be nice to have cwd provided by vertx environment:)

**Comment by pmlopes** [comment]
That should be possible. I'll add it to the process object like node does so we keep the usage simple for js users.

**Comment by pmlopes** [comment]
We shall expose the `vertx.cwd` as that is also respected to follow non js code semantics.
