### ISSUE TITLE
Add maven wrapper as default?

### ISSUE THREAD

**Issue by StephenOTT** [reactiverse/es4x#26]
Using maven wrapper makes the build more reproducible since it does not rely on the locally installed maven version.  Reduces the non-java developer deps as well.

**Comment by pmlopes** [comment]
I believe the script will already looks first for maven wrapper before calling maven, but no wrapper is bundled with it

**Comment by StephenOTT** [comment]
Correct.  I am suggesting that maven wrapper be downloaded automatically when init a project.  Thus reducing the dep of having maven installed or knowing about the wrapper in the first place.

**Comment by pmlopes** [comment]
I agree, once graal in on the path for example, it's the only dependency, as npm is available as a wrapper, so having maven wrapper one could get up and running just with graal on the system (for example).

**Comment by StephenOTT** [comment]
Yes having NPM as a wrapper as well would be a nice option! 💯

**Comment by StephenOTT** [comment]
@pmlopes amazing!
