### ISSUE TITLE
Expected an operand but found export

### ISSUE THREAD

**Issue by siloam** [reactiverse/es4x#264]
I've got strange error. Do I need to use "require" instead of new import/export syntax when I'd like to use local files?

```
Failed in deploying verticle caused by SyntaxError: /Users/MarczakMa/Desktop/test/handler.js:40:0 Expected an operand but found export
export const handler = {
^
/Users/MarczakMa/Desktop/test/handler.js:55:14 Expected ; but found :
    handleTest: ctx => {
              ^
/Users/MarczakMa/Desktop/test/handler.js:58:0 Expected ) but found }
}
^
/Users/MarczakMa/Desktop/test/handler.js:59:0 Expected eof but found }
});
^
```

**Comment by pmlopes** [comment]
Currently `esm` features `import/export` require you to name your files `*.mjs` this way they either get loaded by the ESM loader or the CommonJS loader. The first script to be loaded defines which loader will be used so if you name your initial script as `index.mjs` then all loads after will happen in mjs. If you name your script `index.js` then commonjs is used.

Common js has a small *hack* that transforms `import {...} from...` to `require(...)` calls but it doesn't do anything about `exports`.

I'm currently waiting for the esm support on node to settle and then try to follow as close as possible they way they do things there.
