### ISSUE TITLE
ReferenceError: Java is not defined

### ISSUE THREAD

**Issue by UglyHobbitFeet** [reactiverse/es4x#266]
Hi,

** I'm not sure if a ticket should be submitted here, or in a particular vert.x package. If this is the wrong place, please let me know and I'll move the ticket.

I am creating a VueJs project in Vert.x using es4x-pm (via es4x init).  I have the following file within my project:

myTest.js

    import { FileSystem } from '@vertx/core';
    const result = FileSystem.readFileBlocking(MyFilepath).toString();

I then do an 'npm run build' which is fine and shows me the typical output of:

    > es4x

    ES4X is using graaljs in interpreted mode! Add the JVMCI compiler module in order to run in optimal mode!
    Succeeded in deploying verticle

I then run 'npm start' and my Vue UI shows up as expected.  I then navigate to the 'myTest.js' page (via vue-router)  and am met with the following in my console.

    vue-router.esm.js:2079 ReferenceError: Java is not defined
        at Object.8a64 (module.mjs:18)
        at c (bootstrap:89)
        at Module.<anonymous> (auth.7fd9897a.js:1)
        at Module.4cf9 (auth.7fd9897a.js:1)
        at c (bootstrap:89)

If I navigate to the module.mjs:18 I see the following:

    export const AsyncResult = Java.type('io.vertx.core.AsyncResult');

So, it looks like it's barfing on the first Java call in the vert.x core index file.  

How do I 'define' Java in this instance?

**Comment by pmlopes** [comment]
That's quite odd, `Java` is a builtin type is should always be present. Can you do:

```
es4x versions
```

And list here what the output is?

**Comment by UglyHobbitFeet** [comment]
VM:      OpenJDK 64-Bit Server VM
Vert.x:  3.8.4
ES4X:    0.10.0
graaljs: 19.3.0

**Comment by UglyHobbitFeet** [comment]
FWIW if I copy/paste the FileSystem code shown in the first post directly into the index.js file of my project (where the vertx server starts up), I get a slightly different message.

TypeError: invokeMember (readFileBlocking) on JavaClass[io.vertx.core.file.FileSystem] failed due to: Unknown identifier: readFileBlocking
        at <js> :anonymous(/myPath/myProject/index.js:25:991-1025)

**Comment by pmlopes** [comment]
`FileSystem` is an interface you cannot use it without an instance, the import just returns the typescript declaration. you need to follows the API to get there:

```js
// this only imports the interface (abstract class)
import { FileSystem } from '@vertx/core';

// this gets you a FileSystem instance
const fs = vertx.fileSystem();
// now you can use it:
const result = fs.readFileBlocking(MyFilepath).toString();
```

**Comment by UglyHobbitFeet** [comment]
Possibly a silly question, but where do I import the vertx variable from? Seems to be available in the index.js file (without an explicit import) but I'm not sure how to reference that variable from other files within my project.

**Comment by pmlopes** [comment]
There always a `vertx` global on all scripts.

**Comment by UglyHobbitFeet** [comment]
Unfortunately I get vertx is not defined errors :(

**Comment by pmlopes** [comment]
Can you provide an example showing the issue? I can't reproduce it without it.

**Comment by UglyHobbitFeet** [comment]
I'll try my best to breakdown what's happening (as it may be too tough to create a whole dummy project online)

**index.js** - Contains the vertx code to start up the app like 

     server.requestHandler(app).listen(somePort);

If I add the following lines to the index.js file, they work perfectly.

    const fileSystem = vertx.fileSystem();
    const result = fileSystem.readFileBlocking(someFile).toString()
    console.log(result);

This proves the FileSystem suggestions you made in an earlier post work great!

In the real world, I would like to do the FileSystem call at a later point though. As a rough example I set it up so when I go to a specific URL using Vue Router it would perform the FileSystem logic there:

**router.js**

```
import Vue from 'vue';
import VueRouter from 'vue-router';

Vue.use(VueRouter);

export default new VueRouter({
  routes: [
    {
      path: '/myTest',
      name: 'MyTest',
      component: () => import(/* webpackChunkName: "myTest" */ '@/somePath/MyExample.js'),
    },
  ],
});
```

**MyExample.js**

    /* eslint-disable */
    console.log('In MyExample.js', vertx);

Note that I need the eslint directive above the console statement to even get it to compile, or it barfs with a vertx is not defined compilation error.

When I navigate to http://myUrl/#/myTest using a browser, I see the following error in the console

    vue-router.esm.js:2079 ReferenceError: vertx is not defined
        at Module.4cf9 (MyExample.js:2)
        at c (bootstrap:89)

So, as far as I can tell, I do not have access to the vertx variable at this point. This would prevent me from making the vertx.fileSystem() call.

**Comment by UglyHobbitFeet** [comment]
Does anything stick out about what is shown on my previous post? I'm kinda stuck on this.. :(

**Comment by pmlopes** [comment]
I'm confused, does your error happens on the browser?  I'm asking because you're using vue.

If that's the case, you can't access vertx as vertx is a server side object.

Then I see some module loader too. I've no knowledge on how this module loader work. Perhaps that's what is causing the issue.

I need a working example it'sjust guess work ATM.

**Comment by pmlopes** [comment]
More type information has been added to 0.11.0 which should cover more cases.
