### ISSUE TITLE
How does threading work with Vert.x?

### ISSUE THREAD

**Issue by grumpyrodriguez** [reactiverse/es4x#274]
Does es4x follow the Node's threading model on top of Vert.x? That is, a single thread to run javascript, that can delegate tasks to a number of background threads? 

Vert.x uses a multi reactor model as far as I know, so the verticles can actually end up running on one of the multiple event loops which scales better compared to Node's single event loop (assuming my understanding is correct)

So does es4x run on multiple loops, i.e running javascript on multiple threads, but isolated, or does it use a single thread and run all verticles on that thread? 

Some clarification would be great, could not find this in the docs

**Comment by pmlopes** [comment]
Es4x just replaces java with JavaScript at the user level. Underneath it's plain vert.x. so this means that there's a JavaScript language context per application instance and this can be accessed by all vert.x eventloops (no threads involved just an object instance) so performance is not compromised and graalvm does the final optimizations to generate fast native code.

But indeed the docs are quite scarce and should point more often to the upstream docs.

**Comment by grumpyrodriguez** [comment]
@pmlopes thanks, really helpful. Is my understanding correct? : 
There is a single object representing the Javascript execution context and all vert.x event loops have synchronized access to this object.  

I can see the performance is fantastic, based on the TechEmpower benchmarks but I was curious if this is still based on a single threaded javascript execution model, apparently it is.

**Comment by pmlopes** [comment]
Yes you're correct but there's one small note. As you can imagine many eventloops guessing a single context can put some pressure on the synchronization of the context. To solve this we can instantiate as many scripts/contexts as eventloops to avoid contention. Vert.x already load balances requests per event loop and the eventloops will load balance across instances.

This all happens behind the scenes as it's managed by vert.x anyway.

**Comment by grumpyrodriguez** [comment]
@pmlopes Bingo! This is what I was trying to understand. So there is a mapping between eventloop_x (where x is between 0 and N) and context_x and there are indeed multiple js contexts. 

I thought this would be the best design to aim for but I was not sure if the current approach fits this design. This is what I meant with 

> so the verticles can actually end up running on one of the multiple event loops which scales better compared to Node's single event loop

Thanks for the clarification. A high level architectural overview document would be immensely helpful. Are there any docs are presentations etc that explain how things are wired? (Happy new year btw and thanks for taking to respond on a new year's eve)
