### ISSUE TITLE
Error type in index.d.ts file should be java.lang.Throwable

### ISSUE THREAD

**Issue by exculibar** [reactiverse/es4x#295]
They have different interface, but I'm not found any  java.lang.Throwable declaration
```ts
err.message // for javascript Error type
err.getMessage() // for java.lang.Throwable
```

I found some declarations in node_modules/@vertx/core/inde.d.ts file:
* At index.d.ts file on line 21 - 26
```ts
export interface AsyncResult<T> {
  succeeded() : boolean;
  failed() : boolean;
  cause() : Error | null; //The type [Error] should be [java.lang.Throwable]
  result() : T | null;
}
```

* At index.d.ts file on line 1846
```ts
failure() : Error | null; //The type [Error] should be [java.lang.Throwable]
```

* At index.d.ts file on line 3699
```ts
exceptionHandler(handler: ((res: Error) => void) | Handler<Error> | null | undefined) : HttpClientRequest;  //The type [Error] should be [java.lang.Throwable]
```

This is my package.json file content
```json
{
  "version": "1.0.0",
  "description": "This is a ES4X empty project.",
  "main": "index.js",
  "scripts": {
    "test": "es4x test index.test.js",
    "postinstall": "es4x install",
    "start": "es4x",
    "build": "tsc -w --sourceMap index.ts verticles/*.ts"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "name": "es4x_demo",
  "devDependencies": {
    "@vertx/unit": "^3.8.5"
  },
  "dependencies": {
    "@vertx/core": "^3.8.5",
    "@vertx/web": "^3.8.5"
  }
}
```

Example code: 
Use a non-exist host as the EventBus message, the exceptionHandler will pass an  [ java.lang.Throwable] to the callback function
```ts
/// <reference types="es4x" />
// @ts-check
import { RequestOptions } from "@vertx/core/options";

var client = vertx.createHttpClient();

vertx.eventBus().consumer('http_req', msg => {
  console.log(msg.body());
  var options = new RequestOptions()
    .setHost(msg.body().toString())
    .setURI('/')
    .setPort(443)
    .addHeader('User-Agent', 'Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36')
    .setSsl(true);
  client.get(options, res => {
    res.bodyHandler(buf => { 
      msg.reply(buf.toString('utf-8'));
    });
  }).setTimeout(5000)
    .exceptionHandler(err => {
      console.log(err);
      // msg.fail(500, err.message); // err.message is null 
      msg.fail(500, err.getMessage());
    }).end();
});
```

**Comment by pmlopes** [comment]
I assumed wrong that the js Error would match the Throwable at least the printStackTrace call or the console.trace call.

We need a extra definition for throwable and a interoperability Error -> Throwable when crossing from js to java.

**Comment by pmlopes** [comment]
@exculibar in https://github.com/reactiverse/es4x/commit/7a1ef7348c8bc9f07233894a4a06a481f3504463 I'm exposing the `Throwable` as a known type but not instantiable from `js` and will update the generated definitions to use it instead of `Error`.

I'm still working on allowing both `Throwables` and js `Errors` to be passed up to the java layer interchangeability.

**Comment by exculibar** [comment]
> @exculibar in [7a1ef73](https://github.com/reactiverse/es4x/commit/7a1ef7348c8bc9f07233894a4a06a481f3504463) I'm exposing the `Throwable` as a known type but not instantiable from `js` and will update the generated definitions to use it instead of `Error`.
> 
> I'm still working on allowing both `Throwables` and js `Errors` to be passed up to the java layer interchangeability.

Nice work!  ^_^

**Comment by exculibar** [comment]
@pmlopes 
Seems missing the file **[node_modules/@types/es4x.d.ts]**  when I fresh installed @vertx/core in an empty folder.
```json
"dependencies": {
    "@vertx/core": "^3.8.5",
    "@vertx/web": "^3.8.5"
}
```
