### ISSUE TITLE
can es4x work alongside spring/hibernate?

### ISSUE THREAD

**Issue by darrencruse** [reactiverse/es4x#296]
I have a 10 year old app that started life as a traditional SpringMVC+Hibernate deployed as WAR file in a servlet container kind of app.

Considering it's main purpose was serving JSON REST services we later added use of the Ringo (Rhino based framework), running the javascript from a servlet filter that at times would call back into the Spring/Hibernate code.

That served us well but Ringo never became popular we'd ideally like to replace that with something newer and (ideally) more popular (i.e. with a bigger community and better support behind it).

At first I thought GraalVM nodejs might work but I now understand there could/would be issues with e.g. the blocking I/O hibernate would do against the database.

From what I've described does es4x sound like a better fit?

e.g. googling I don't really see any help about using Spring/Hibernate with GraalVm nodejs, but at least I do see a little about such things with vert.x

But otoh will I not face similar issues?  (i.e. vert.x is still a non-blocking approach using netty right)

Thanks (new to es4x/vert.x/graal appreciate some advice),

Darren

**Comment by pmlopes** [comment]
Hi,

Theoretically nothing should block you from using es4x with spring/hibernate. There are a few potential caveats that need to be verified before hand. es4x runs on vert.x so as you noticed it's API will be mainly asynchronous, this means that the blocking nature of spring/hibernate will not provide the best performance.

The graaljs engine is designed to operate on a single thread. Multiple threads can access it but only 1 at a time can be on the execution context, this means that if you start your application from spring and it's thread pools, you need to have several engines (or es4x instances, or serialize all the calls, which can be a bottleneck).

If you want to see more about interop, here's an example of es4x, java grpc and java graphql 

https://github.com/pmlopes/es4x-grpc-graphql

As you can see it's not that different from nashorn/rhino...

**Comment by darrencruse** [comment]
Thanks I took some extra time to think about your reply...
