### ISSUE TITLE
is it possible to use(to run) the es4x for nodejs rest api application ?

### ISSUE THREAD

**Issue by Narasinha** [reactiverse/es4x#302]

**Comment by McSneaky** [comment]
Yes and no.
You can make it work, but it's not a drop in replacement. A lot of existing NodeJS REST APIs and frameworks rely on some really NodeJS specific stuff, like built in `net` and `crypto` etc libraries.

You have to remove most of those Node specific things with your own code / libraries and also get rid of such calls in libs in node_modules folder. Here's good example how to alias those modules to your own code: https://github.com/reactiverse/es4x/tree/develop/es4x/src/test/resources/alias especially `es4xAlias` in `package.json`
