### ISSUE TITLE
Where is the api docs ?

### ISSUE THREAD

**Issue by laiweiwei** [reactiverse/es4x#303]
Thanks for your great job!
I visit the api docs page follow your offical website user guide, then i got 404, 
https://github.com/reactiverse/es4x/blob/master/@vertx/core/index.html, 
please tell me where can i get them?

**Comment by pmlopes** [comment]
There's an issue with the current vuepress service worker cache. If you refresh the page usually it gives you the right file.

In the meantime I'm adding the basic manual to the generation so I hope to update the website soon.

**Comment by pmlopes** [comment]
@laiweiwei the original docs have been automatically translated from the official upstream. Please expect to find some errors here and there and they need a manual review now.

In the mean time you can already find most of the information here: https://reactiverse.io/es4x/manual

I'll close this issue for now and will continue improving the docs as new releases happen.
