### ISSUE TITLE
@vertx/mongo-client - Need method to get a single collection

### ISSUE THREAD

**Issue by UglyHobbitFeet** [reactiverse/es4x#321]
From what I can gather, you have to manually mongoClient.getCollections() and troll through everything to find what you're looking for.  It would be much more helpful to have a mongoClient.getCollection(collectionName) method.

**Comment by pmlopes** [comment]
We just expose the java api to the script engine, adding new stuff should be done upstream. If that happens on a new release of es4x it will automatically available
