### ISSUE TITLE
@vertx/mongo-client No easy way to get new collection

### ISSUE THREAD

**Issue by UglyHobbitFeet** [reactiverse/es4x#322]
If I create a new collection via mongoClient.createCollection("someName"),  the handler is an async void.  That means I have to call mongoClient.getConnections() and troll through it looking for the newly added one.  This is especially frustrating because my code is currently:

```
  // get collections
   // if collection doesnt exist, create collection
      // get collections again
        // loop through them and hope it's there
```

This would be much simpler if createCollection() returned the collection

**Comment by pmlopes** [comment]
We just expose the java api to the script engine, adding new stuff should be done upstream. If that happens on a new release of es4x it will automatically available
