### ISSUE TITLE
@vertx/mongo - Javascript package should not return java object types

### ISSUE THREAD

**Issue by UglyHobbitFeet** [reactiverse/es4x#323]
In my javascript code, I'm doing something similar to the following...

     import { MongoClient } from '@vertx/mongo-client';
     
     someFunction() {
        mongoClient.find("someCollection", "someQuery", (res) => {
          if (res.succeeded()) {
            console.log(res.result());
          }
       });

Which gives me a Java List Object:
```
  add: [Function],
  remove: [Function],
  get: [Function],
  clone: [Function],
  indexOf: [Function],
  clear: [Function],
  isEmpty: [Function],
  lastIndexOf: [Function],
  etc...
```

That means I now have to start writing java conversion code in my javascript using list.size() / list.get().

I would expect that a javascript package would return javascript results. Furthermore java results would be completely non-intuitive for someone who does not know that language and they would not know how to proceed.

Doing a conversion also results in messages like `"Thread Thread[vert.x-eventloop-thread-0,5,main]=Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 4730 ms, time limit is 2000 ms"`

Here's a 'simplified' example as I don't know a better way to do this and it still results in the thread blocking error message.... FWIW I also tried with executeBlocking() and got the same issues.

```
someFunction() {
  return new Promise ((resolve, reject) => {
    mongoClient.find("someCollection", "someQuery", (res) => {
      if (res.succeeded()) {
        // Convert from Java to Javascript
        const context = vertx.getOrCreateContext();
        context.runOnContext(v1 => {
          const results = [];
          for (let i=0; i < res.result().size(); i++) {
            results.push(res.result().get(i));
          }
          resolve(results);
        });
      } 
    });
  });
}
```

**Comment by UglyHobbitFeet** [comment]
So I came across this in the javascript docs and it seems to work. I usually don't look there as it's mostly outdated and the calls more closely resemble the java docs

```
    Array.prototype.forEach.call(res, function(json) {
      console.log(JSON.stringify(json));
    });
```

**Comment by pmlopes** [comment]
Hi, the response is indeed a java `List` however, you should be able to iterate it just like a normal js `Array`. What makes it strange to the logs is that the `console.log` function is not taking it to consideration and printing the internal java properties instead of showing it as a js `Array`.

**Comment by UglyHobbitFeet** [comment]
Yeah, it didn't let me do a simple for loop. Not sure why, but it may have
something to do with the way it's benign treated in the console log as you
mentioned.

**Comment by pmlopes** [comment]
The current develop branch uses graal proxies to show vertx json types as native types.
