### ISSUE TITLE
Is it possible to passed a JS Promise as a ES4XFuture runtime type to java method?

### ISSUE THREAD

**Issue by laiweiwei** [reactiverse/es4x#328]
@pmlopes Thanks for your great job!
I have a Java method like this:
```
public doSth(Function<Object, Promise> fn) {
    Promise p = fn.apply(...);
    p.future().onSuccess(...)
}
```
This method will be called both in Java or JS.
It's good in java case to call this method, but strange in JS case. 

I can use Java.type('io.vertx.core.Promise').promise() which will create ES4XFuture instance by `SPI` as a parameter passed to Java method.
```
hello(obj => {
    const p = Java.type('io.vertx.core.Promise').promise();
    jdbcClient.query(..., (asyncResult) => p.complete(asyncResult.result()))
    return p;
})
```
But as usually(this is what i expected), the js code will be like this : 
```
hello(obj => {
    const p = new Promise((resolve, reject) => {
        jdbcClient.query(..., (asyncResult) => resolve(asyncResult.result()));
    });
    return p;
})
``` 
Is it possible in ES4X ?

**Comment by pmlopes** [comment]
Hi, currently you can't. But I think we can have it with a small modification that would not be to different to you.

First we need to clarify the vertx types.

* `Promise` the writable side (where the result is set.
* `Future` the readable side, where you react to the outcome. 

So the main difference here is that `js` `Promise` is similar to vertx `Future`. 

Now in vertx `Promise` is used as a method parameter, and `Future` as a method result.

If your code would be changed to :

```java
void mth(Function<Object, Future> fn);
```

Then maybe graaljs can allow us to write the simple transformation from js promise/thenable to vertx future.

**Comment by laiweiwei** [comment]
Thanks for your help, it works.

**Comment by pmlopes** [comment]
It doesn't work because there's no automatic transformation yet. But I think we could add it.
