### ISSUE TITLE
ES4X Windows Install

### ISSUE THREAD

**Issue by benswen** [reactiverse/es4x#330]
Just installed on Win10 using instructions [found here](https://reactiverse.io/es4x/get-started/install.html#verify-the-installation). After install, it says to test the install by typing `es4x --help`. This does not work on Windows. I can manually add a path in SysEnv to the executable, but I don't know what the entry point is?

**Comment by yuangu** [comment]
I found not work  according to his documents.
it's work to me. first install node.js and npm.
```
# add es4x-pm globally
npm install -g es4x-pm
# create a generic project
mkdir my-app
cd my-app
# init the project
es4x init
# add other dependencies...
npm install @vertx/unit --save-dev
npm install @vertx/core --save-prod
# will trigger the download
# of the java dependencies
npm install
```

**Comment by nythrox** [comment]
I had problems getting an es4x server to run but it worked when I had the exact version of graalVM on my computer that was used by the version of es4x I was using (es4x 0.10.1 and graalvm 19.3)

**Comment by benswen** [comment]
@yuangu That did not work for me. 
@nythrox Thanks, I'll give that a try. However, I'm not sure exactly how to find out which version of GraalVM es4x 0.11.0 is expecting?

**Comment by nythrox** [comment]
@benswen You can check the version of GraalVM being used on the releases
https://github.com/reactiverse/es4x/releases

**Comment by benswen** [comment]
@nythrox Thanks. That's the version I have installed. Any other thoughts?

**Comment by nythrox** [comment]
@benswen Did the global installation of es4x-pm work? Did it show any errors? Can you confirm that it's installed on your computer by running npm list -g?

**Comment by pmlopes** [comment]
In the latest docs, I've recommended to install jabba as a simple tool to install and/or switch JVMs. The tool os cross platform and works well on windows too:

https://github.com/shyiko/jabba
