### ISSUE TITLE
Types missing enum and Duplicate class name  Redis client 3.9.0

### ISSUE THREAD

**Issue by Dylancorbus** [reactiverse/es4x#334]
node_modules/@vertx/redis-client/options.d.ts:156:10 - error TS2305: Module '"../../../../../../../Users/dylancorbus/Desktop/matching-service/node_modules/@vertx/redis-client/enums"' has no exported member 'Type'.

156 import { Type } from './enums';
             ~~~~

node_modules/@vertx/redis-client/options.d.ts:240:14 - error TS2300: Duplicate identifier 'RedisOptions'.

240 export class RedisOptions {
                 ~~~~~~~~~~~~

node_modules/@vertx/redis-client/options.d.ts:419:14 - error TS2300: Duplicate identifier 'RedisOptions'.

419 export class RedisOptions {
                 ~~~~~~~~~~~~

**Comment by pmlopes** [comment]
Duplicate classes have been addressed on vert.x 4.0.0
