### ISSUE TITLE
Add mvn dependency download feature

### ISSUE THREAD

**Issue by Dylancorbus** [reactiverse/es4x#337]
I want to import java jars into my es4x js project since a lot of node modules are not compatible. I would be nice if there was a capability to add a mvn dependencies section that would get parsed and the appropriate jars would get downloaded and then you could just access them like `Java.type('com.google.firebase.FirebaseDatabase')` not sure how to add the jars in the project.

**Comment by pmlopes** [comment]
This is already possible in your package son add a list:

```
{
  dependencies: [
    "groupId:artifactId:version"
  ]
}
```

You can add as many as you like and they will properly resolved from maven and required dependencies will be included.

**Comment by pmlopes** [comment]
In order to address this we need to document it properly.

**Comment by pmlopes** [comment]
the website docs document this
