### ISSUE TITLE
Allow async undeploy hook: [was] Shutdown Hook

### ISSUE THREAD

**Issue by mikearnaldi** [reactiverse/es4x#360]
How would I register a shutdown hook?

**Comment by pmlopes** [comment]
@mikearnaldi, do you mean a JVM shutdown hook? or a verticle undeploy?

A verticle undeploy can be done as:

```js
process.on('undeploy', function () {
  print('onStop');
});
```

Currently you can't do async calls there but we could try to fix it to allow...

**Comment by mikearnaldi** [comment]
That would work if async is allowed, I was interested in the lifespan of the verticle
