### ISSUE TITLE
Support NODE_PATH variable

### ISSUE THREAD

**Issue by stephenh** [reactiverse/es4x#38]
Hi, I'm trying es4x with an existing graphql application and our old boot file was:

```
export NODE_PATH=build/
node build/server.js
```

It's not a huge deal, but doing `vertx-scripts launcher run build/server.js` from our root project directory can't find the compiled files in `build/` so I have to `cd` into `build` and then run `vertx-scripts launcher run server.js`.

Not a blocker but just thought I'd mention it. Maybe `NODE_PATH` is too much "pretending to be like node" and would be confusing, but some sort of equivalent would be nice. (I also recently tried graal's `node` replacement and it supported `NODE_PATH` just fine, although that makes sense as they are purposefully trying to be a `node` drop-in.)

**Comment by pmlopes** [comment]
https://github.com/nodejs/node-v0.x-archive/blob/master/lib/module.js

It seems I'm handling it already but it is wrong, the variable should take precedence but it is currently not the case

**Comment by pmlopes** [comment]
@stephenh could you verify that the test is correct:

https://github.com/reactiverse/es4x/blob/31b9546f45a1f07dd3719545629a3bc7d6a515c1/src/test/java/io/reactiverse/es4x/test/CommonJsNODEPATHTest.java

If I understand it correct, the NODE_PATH takes precedence and changes the default start up lookups so if a module named `path` is defined in a path `dist` and there is a module with same name in the current working dir and `node_modules` that module from the `dist` is to be preferred.

**Comment by stephenh** [comment]
Thanks for taking a look at this! That makes sense in terms of precedence but I'm admittedly am not an expert.

I bumped to `3.5.4` in my `pom.xml` file and realized the difference is that this works:

```javascript
import { USER_UUID_HEADER } from './lib/headers';
console.log('FOOFOO' + USER_UUID_HEADER);
```

But this does not:

```javascript
import { USER_UUID_HEADER } from 'lib/headers';
console.log('FOOFOO' + USER_UUID_HEADER);
```

Now that I know that, I can just change our imports to have `./` to keep prototyping, but it'd also be nice to have parity with node (although the `./` prefix is admittedly more explicit). Thanks!

**Comment by pmlopes** [comment]
I've to document the `import` properly, the "support" for import is not according to the `ES6` spec, in fact what is happening behind the scenes is that those imports are translated to `commonjs` `require` statements and are because of that, synchronous loads. so the `./` in this case matters as it defines which path to look at.

**Comment by stephenh** [comment]
Ah okay; FWIW I pasted TS code but I do transpile with babel to `require("lib/headers")` statements for both existing-node + prototype-es4x, so my suspicion is that its also commonjs/require behavior to let the `./` prefix be optional.
