### ISSUE TITLE
BUG: deprecate adapt function of ESModuleIO readFile

### ISSUE THREAD

**Issue by frank-dspeed** [reactiverse/es4x#390]
::: warning ES6 module syntax can be used in .js files. ES4X will translate those to commonjs require() statements however exports will not be translated. This feature is only to assist working with IDEs that can perform auto import such as Visual Studio Code. :::

This interop breaks the default interop that should be there when we use dynamicImport

import() can import CJS and ESM it is inside the CJS and ESM Context it should always work.

# es4x dynamic import broken interop 
ESM & CJS can not  dynamic import additional CJS modules inside it also accessing module object inside cjs breaks graalvm silent when loaded via dynamic import inside ESM

JS can also not dynamic import CJS same behavior!
|syntax|Works in cjs | works in esm |Should Work in CJS| Should Work in ESM|Load ESM|Load CJS
|----|----|----|----|----|----|----|
|import|x|x||x|x|x
|import()|x|x|x|xx|x
| require|x||x|||x

- import
  - should NOT work inside CJS deprecate the adapt stuff
  -  should be able to import esm  **** Works ****
  - should be able to import CJS **** dont works ***
  - no named exports from CJS aka syntacticImports from typescript always return default
  - should error when used like this with cjs import { x } from 'x' 
  - only import x from 'x ' should work 
  - import * as x from 'x' should work but export default
  - import { default as x } from 'x' should work
- import() 
  - should work inside CJS with ESM  *** Probally Broken by adapt but returns with wirred behavior***
  - should work inside CJS with CJS *** Probally Broken by adapt but returns with wirred behavior only returns ESM but executes***
  - should work inside ESM with ESM *** Looks Working ***
  - should work inside ESM with CJS  *** Probally Broken by adapt but returns with wirred behavior only returns ESM but  
  - should be able to import cjs and esm in case of cjs will always return default as namespace === module.exports = exports

require can only load cjs 

## Reproduce able example

module.js
```js
module.exports = { str: 'myString'}
// When the following line gets uncommented the secund console log will not get called silent fails when this file gets imported via dynamic import() no matter if from CJS or ESM
//console.log('ctx',module)
console.log('The Import works correct as this sideEffect gets executed')
``` 

index.mjs
```js
//then does not even get called sideEffects do execute
import('./module.js').then(function(x) { console.log('t',x)}) // then does not get called { default: { str: 'myString'}}
export const esm = 'Works' 
```

index.js
```js
// Will not work
//then does not even get called sideEffects do execute
import('./module.js').then(function(x) { console.log('t',x)}) // then does not get called { default: { str: 'myString'}}

//This will work 
console.log(require('module.js'))
import('./index.esm.js').then(function ({esm}) { console.log(esm) })
```

## Conclusion
dynamicImport import() at present only supports ESM no matter if used in ESM context or CJS
i think also that the current dynamic import implementation does not hornor .mjs === ESM and .cjs === commonjs(require,module)

**Comment by frank-dspeed** [comment]
https://github.com/graalvm/graaljs/blob/master/docs/user/JavaScriptCompatibility.md#compatibility-extensions

load() can be used maybe to get better results and with url support

**Comment by laiweiwei** [comment]
https://github.com/reactiverse/es4x/pull/385

**Comment by frank-dspeed** [comment]
it would be great if import and import() would adapt cjs with a ESM Wrapper and if require would adapt with a CJS  Wrapper
