### ISSUE TITLE
Translate docs to your own language

### ISSUE THREAD

**Issue by pmlopes** [reactiverse/es4x#404]
Many (if not most) developers speak English as second language. Having the [docs](https://github.com/reactiverse/es4x/tree/develop/docs) translated to your own language would help lowering the barrier to new users.

Currently only English docs are up to date, the existing sub docs:

* `pt` - Portuguese
* `zn` - Chinese

Are out of date and could receive a review. The work doesn't require any programming knowledge, or `es4x` specific knowledge.

Fork the repo, open the `docs` folder clone the folders, except language codes or `.vuepress`.

**Comment by Geshii** [comment]
will translate it in french

**Comment by eduaugustus** [comment]
I'' Translate to Brazil Portuguese

**Comment by Trustidiong** [comment]
Would you take a translator in sign language? I would like to come in there.

**Comment by ILGO0413** [comment]
Will translate it to Russian

**Comment by pmlopes** [comment]
@Trustidiong (pardon my lack of knowledge here), how would that work?, is there any special textual representation of sign language we can use for the web?

**Comment by Petros0** [comment]
Will translate in Greek(gr) :)

**Comment by kpencak** [comment]
Gonna translate it to Polish (pl)

**Comment by Kara3** [comment]
I would translate it in Bulgarian.

**Comment by AntoniosBarotsis** [comment]
@Petros0 I did not see your commend and have already started a greek translation, do you want to split the work in half?

**Comment by Petros0** [comment]
@AntoniosBarotsis Hey, no problem. Go ahead finish the `advanced` directory. I finished the `README.md` in the root directory. We can split also the `get-started` directory.

**Comment by AntoniosBarotsis** [comment]
Nice! I can work on the first 4 files of ``get-started``: ``README``, ``debug``, ``hello-world`` and ``install`` as well as ``advanced`` and you work on the ``api``  as well as the rest from ``get-started``

**Comment by Trustidiong** [comment]
There is no textual representation of sign language, actually. We translate text into sign language videos.
    On Friday, September 25, 2020, 08:02:52 AM GMT+1, Paulo Lopes <notifications@github.com> wrote:  
 
 


@Trustidiong (pardon my lack of knowledge here), how would that work?, is there any special textual representation of sign language we can use for the web?

**Comment by pmlopes** [comment]
@Trustidiong we don't host videos, for that it would make more sense a YouTube channel, but currently own one either.

**Comment by Lukaesebrot** [comment]
Will translate it into german.

**Comment by Geshii** [comment]
#415

**Comment by fedGL** [comment]
I read your post on dev.to and I'm happy to help! I translated all docs inside the _advanced_ folder plus the main README to Spanish. I'll do a PR :D

**Comment by pmlopes** [comment]
Great @fedGL ! Thanks!

**Comment by pmlopes** [comment]
Thanks to everyone who participated! :+1:
