### ISSUE TITLE
GraalVM required

### ISSUE THREAD

**Issue by UglyHobbitFeet** [reactiverse/es4x#409]
I'm having issues with vue-cli-service and GraalVM playing nicely with each other.  I'd rather use my Java8 instance.  The docs for es4x say we can use either GraalVM or Java>=8.  However, es4x doesn't seem to accept a regular Java version and is now erroring out if it doesn't find GraalVM v.20.2.0

**Comment by pmlopes** [comment]
A new release 0.13.2 addresses this issue.

**Comment by UglyHobbitFeet** [comment]
Awesomesauce, thanks!
