### ISSUE TITLE
Importing native node modules 

### ISSUE THREAD

**Issue by stephenh** [reactiverse/es4x#41]
Hello again; sorry, this isn't quite an issue, but wanted to see your thoughts on this.

I'm working on booting our apollo GraphQL app on es4x to see how it performs. I'm writing a vertx -> apollo adapter (similar to their express adapters/etc) for mounting apollo's core GQL logic as a vertx-web handler and then will also write an "JS http call -> vertx http client" adapter for our outgoing microservices (we currently have them all go through `request-promise`, but it should be pretty easy to write something that looks like `request-promise` but uses the vertx client impl).

So, I think I've got the major inputs/outputs covered, but before getting that far, I'm also running into native node modules that our npm dependencies pull in; we generally don't use any custom-compiled/native node C API modules (AFAIU), but we do using some of these:

https://github.com/graalvm/graaljs/tree/master/graal-nodejs/doc/api

Particularly `crypto` is what I'm running into now, because the JS `uuid` npm package pulls it in to do UUID generation.

Some of the npm packages have browser fallbacks, e.g.:

https://github.com/kelektiv/node-uuid/blob/master/package.json#L35

So I'm curious:

a) do you think es4x can/should use the `browser` fallback if its needed/available, and

b) do you think es4x will end up exposing/pulling in some of the graaljs-provided node modules (such as `crypto`), or does that bring a bunch of other node dependencies/complexity (or worse runtime overhead?) that you don't want/need?

 Thanks; understood you're in very early stages, so I'm probably getting ahead of things by trying to boot up a full-fledged/existing application, so these sort of issues might be premature.

**Comment by pmlopes** [comment]
Hi, I totally haven't looked at native modules so I can't tell any eta or what to expect. Regarding module alias, that is something npm doesn't support but requirejs does... maybe we could think of a registry of alias for ES4X / Vertx modules or let it be more user managed with a custom key on the package json that would only alias on that context. 

But this would be a big drift from node though...

**Comment by pmlopes** [comment]
@stephenh I've been reading about the `browser` property and looked at the specific example you gave and I think falling back to `browser` isn't a good idea because of several factors:

1. code will make assumptions that objects like `Window`, `XMLHTTPRequest`, etc... are available
2. less performant/secure APIs are implemented (like the crypto in UUID)

So I think the best is to either:

* provide a couple of polyfills (hard to maintain and duplicates the work of graal-node)
* define a `es4x-alias` key in the package json that maps `module-a` to `module-b`

The later approach seems easier to implement and if there is demand the community could push their own alias, for example, the `uuid` could be aliased to `es4x-uuid` which in this case it all about implementing a couple of functions and delegate to the JVM `java.util.UUID` class for the heavy work.

**Comment by stephenh** [comment]
Agreed falling back on `browser` isn't a good idea and an `es4x`-specific alias is a good idea.

Naively, it seems nice to pull graal-node's existing polyfills if possible, but agreed it's a slippery slope. E.g. `crypto` seems "core infra"-ish? like something many existing (server-side) npm packages probably use/assume is available, but then do you pull in the `http` module? The whole point of es4x is using the vertx netty/http stack, so that seems kind of silly...

From a potential user perspective, I'm happy to write es4x/vertx glue for our specific app input/output, but once it comes to "well, we pull in N dependencies and they all assume a ~node environment", the cost factor goes up pretty quickly... 

E.g. I basically want node but with es4x/vertx/netty for the web stack (and graal for the vm, but there is admittedly already graal-node for that)...

Not sure if that fits your vision for es4x, e.g. if you want to be purposefully a clean break of "not node and instead just pure vertx + jvm libs" or if the fuzzier "node with a better vm/http stack" is a line you'd try and walk (in which case, maybe you could start with graal-node as a basis for es4x and then layer in es4x?).

(For context of why I'm here at all, I recently benchmarked our GQL app on node-v8 vs. graal-node and graal-node was ~2x latency/cpu, so my curiosity given you're pretty amazing benchmark results is that if I can get our same GQL app but on ~"graal-node + es4x + vertx + netty" then maybe that would be able to achieve lower cpu/latency than node-v8 and get us some perf/operational cost wins.)

**Comment by pmlopes** [comment]
@stephenh is it possible to see how you're building this gql server? I'm interested to see the issues you're facing and it could help me to improve the workflow.

**Comment by pmlopes** [comment]
@stephenh could you please have a look at #43

**Comment by pmlopes** [comment]
There's now support for graphql from https://github.com/vertx-graphql and will be also available for all vertx stacks with https://github.com/vert-x3/vertx-web/issues/1175
