### ISSUE TITLE
(feat) filesystem should support custom js file with load resolve hook

### ISSUE THREAD

**Issue by frank-dspeed** [reactiverse/es4x#410]
-Dvertx.loader=./path/hook.js

```js
exports default {
  // importer === resolvedPath of the Importing Module or the module that uses require import 
  //Type: (specifier: string, importer: string | undefined) => resolvedPath<string> 
  async resolve(specifier,importer) {
    return Promise.resolve('resolvedPath')
  },
  // import === resolvedSpecifier to realpath returns Promise<String> with code
  async load(realPath) {
    return Promise.resolve('codeContent ')
  }
}
```  

should run in its own context then i can create adapters for typescript and rollup and webpack. pnp and any other module system even maven :)

Closes: https://github.com/reactiverse/es4x/issues/390

**Comment by pmlopes** [comment]
For ESM, I'm using graaljs native loader and last time I looked at it there were no hooks. Maybe if there are now or they implement it we can easily add that.

**Comment by frank-dspeed** [comment]
@pmlopes your right but we can still support that with some tricks we can keep the issue open as that hook is the most best solution and for require we should at last some how support that it throws when it loads ESM

**Comment by frank-dspeed** [comment]
@pmlopes oh and this was only about the filesystem so this requests simply to enable that hook on the filesystem to allow additional loaders with the url pattern

it looks like import css from 'my-module/my-css.css!css'

the ! added after the extension defines a custom loader.

**Comment by frank-dspeed** [comment]
Not needed anymore found a better way to implement that. i will go for a custom loader in userland
