### ISSUE TITLE
esx not found in NPM

### ISSUE THREAD

**Issue by saikat1978** [reactiverse/es4x#428]
Trying to follow the exact paths mentioned in your git repo to run a hello world. When I run - npm install, it gives the following error - 

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@vertx%2fcreate - Not found
npm ERR! 404 
npm ERR! 404  '@vertx/create@0.13.2' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'myapp'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sc1000255563/.npm/_logs/2020-10-13T23_33_20_950Z-debug.log

**Comment by pmlopes** [comment]
Hi, where did you saw `@vertx/create`? It should be `@es4x/create`.

If it was a typpo somewhere in the docs, I'd like to fix it.

**Comment by mihai1voicescu** [comment]
Running the init script produces `@vertx` namespaced deps:

```
mihaivo@Mihais-MacBook-Pro es4xample % npm init @es4x project             
npx: installed 1 in 3.869s
mihaivo@Mihais-MacBook-Pro es4xample % cat package.json 
{
  "name": "es4xample",
  "version": "1.0.0",
  "private": true,
  "description": "A barebones es4x application",
  "main": "index.js",
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@vertx/core": "3.9.3"
  },
  "devDependencies": {
    "@vertx/create": "0.13.2",
    "@vertx/unit": "3.9.3"
  },
  "scripts": {
    "postinstall": "es4x install",
    "start": "es4x",
    "test": "es4x test index.test.js"
  }
}
```

**Comment by UglyHobbitFeet** [comment]
I was also about to submit a bug for it.
Doing 'npm init @es4x project' generates a package.json with 
```
  "devDependencies": {
    "@vertx/create": "0.13.2",
```

**Comment by UglyHobbitFeet** [comment]
FYI the temp workaround is to change @vertx/create to @es4x/create in your package.json file

**Comment by saikat1978** [comment]
> FYI the temp workaround is to change @vertx/create to @es4x/create in your package.json file

The temp workaround .... well .... it works. Thanks!

**Comment by saikat1978** [comment]
No other issues. Closing.
