### ISSUE TITLE
ES4X-PM npm install

### ISSUE THREAD

**Issue by UglyHobbitFeet** [reactiverse/es4x#435]
If you do an npm install es4x-pm you will get 0.13.0
However, you can download es4x-pm 0.13.3 from the latest releases on github
This means npm is out of sync with what's available via github.

1. The reason this came up is that I am working on an offline machine which has npm access, but not direct access to the latest github release. It would be great if I could just get everything from npm.

2. I noticed in this ticket (https://github.com/reactiverse/es4x/issues/433) that es4x was being downloaded in both stage 1 (via @es4x/create dependency in my package.json) and stage 2 (via es4x-pm github download).  I would like to use the es4x downloaded from stage 1 in stage 2.

3. es4x-pm and @es4x/create look extremely similar to me except for 2 additional files in the bin directory.  Is es4x-pm being deprecated? If so, can its additional bin files be moved over to the @es4x/create project? That way 2 different es4x projects don't have to be downloaded.

**Comment by pmlopes** [comment]
`es4x-pm` should be deprecated on npm to give place to `@es4x/create`. The goal is to be more npm friendly. 

For example, using this new name allows us to do:

```
npm init @es4x 
```

To create a project. I should issue a npm deprecate on `es4x-pm`. 

The new package is also npx compliant so you can run it without install.

**Comment by UglyHobbitFeet** [comment]
Thanks for the response. I'm unfamiliar with npx.  Would this allow bypassing of direct github download?

**Comment by UglyHobbitFeet** [comment]
Or betetr yet, can @es4x create be used instead of the es4x-pm package?

**Comment by pmlopes** [comment]
On docker, the package is downloaded from github to avoid it be added to the final image. It saves 3~4mb and reduces a few dependencies. 

For normal usage, on your package json. You should just have in devDependencies `@es4x/create`. No `es4x-pm`.

**Comment by pmlopes** [comment]
On master I've improved the install command and there's no more duplicated jars.

**Comment by UglyHobbitFeet** [comment]
Thanks for taking a look at this. Is there any way to avoid using es4x-pm if it's deprecated in favor of es4x/create? Currently the Dockerfile has a direct link to github which does not work in an offline environment (that has mirrors for npm).

**Comment by pmlopes** [comment]
You can manually install it, you can get it from:

```
curl https://github.com/reactiverse/es4x/releases/download/${ES4X_VERSION}/es4x-pm-${ES4X_VERSION}-bin.tar.gz
```

or 

```
npm install -g @es4x/create
```

or curl from maven central:

```
https://repo1.maven.org/maven2/io/reactiverse/es4x-pm/0.13.3/
```

Note that maven `es4x-pm` is the same as npm `@es4x/create`, I may align maven to be `es4x-create` just to the sake of aligning names on the future

**Comment by UglyHobbitFeet** [comment]
Correct me if I'm wrong but es4x-pm is not exactly the same as es4x/create.
For example, the es4x/create is missing the es4x command in the bin
directory, which is needed for the docker.

**Comment by pmlopes** [comment]
Ah that's how npm works. The tar/zip include 2 scripts: es4x and es4x.cmd. However a npm package defines a bin script: es4x-cli.js and npm links a auto generated es4x and es4x.cmd at install.

The js implementation should be as close as possible to the scripts.

Here's the sources:

https://github.com/reactiverse/es4x/tree/develop/pm/src/assembly/bin

**Comment by UglyHobbitFeet** [comment]
I think that's part of the problem I'm having. In the dockerfile:

 - if I curl the es4x-pm I can use es4x fine. That's because the beginning of the es4x file has **#!/usr/bin/env bash** 
 - if I download @es4x/create from npm and run node_modules/.bin/es4x the beginning of the es4x file has **#!/usr/bin/env node**.  The dockerfile barfs because node isn't found (because it is using a jvm layer and not an node one).

Ideally I'd like to download the @es4x/create and use the es4x with the bash and not the node.

**Comment by pmlopes** [comment]
Yes the one with node is generated by npm at install. That's how npm works and you can't override it. (Well you can for shell but it will not work on Windows)

**Comment by UglyHobbitFeet** [comment]
How can one override it for shell? Perhaps I could do that?

**Comment by UglyHobbitFeet** [comment]
Or is it possible to bundle the es4x bash file with the @es4x/create? Perhaps call the script es4x-bash? That way the user would have a choice and either execute es4x or es4x-bash.

**Comment by pmlopes** [comment]
This is a limitation of npm. The scripts are available on github release page and can be used that way without npm involved.

There isn't much I can do ATM.
