### ISSUE TITLE
Typos in package.json files

### ISSUE THREAD

**Issue by UglyHobbitFeet** [reactiverse/es4x#438]
JS
https://github.com/reactiverse/es4x/blob/develop/pm/src/main/resources/META-INF/es4x-commands/init/js/package.json

TS
https://github.com/reactiverse/es4x/blob/develop/pm/src/main/resources/META-INF/es4x-commands/init/ts/package.json

I'm assuming the dependencies should change from @vertx/create to @es4x/create

**Comment by pmlopes** [comment]
Should be fixed on the current RC release.
