### ISSUE TITLE
does it conflict with typescript?

### ISSUE THREAD

**Issue by fantasy0v0** [reactiverse/es4x#459]
![Screenshot from 2020-11-23 10-09-36](https://user-images.githubusercontent.com/9549027/99924149-021f6400-2d74-11eb-8342-c0fe98e23898.png)

Version: 3.9.4
conflict when i install other typescript package

**Comment by fantasy0v0** [comment]
maybe can add "@types/node": "*" in dependencies

**Comment by pmlopes** [comment]
Hi, I can't really delete those, because if you don't use any dependency that would pull `@types/node` then it would also fail. I think I need to annotate those overrides as allowed to be ignored on error.

**Comment by pmlopes** [comment]
I'll check if adding `// @ts-ignore` on those types will make it safe or not.

**Comment by pmlopes** [comment]
I've added those to `CR2`
