### ISSUE TITLE
es4x Startup failed

### ISSUE THREAD

**Issue by xjy12345654** [reactiverse/es4x#462]
I installed it according to the example. jdk11.06 but npm start failed

![20201201174151](https://user-images.githubusercontent.com/38834664/100723412-b10b1200-33fc-11eb-92e7-e2431c393a5a.png)

**Comment by fantasy0v0** [comment]
@xjy12345654 
你用的是哪个版本？
what version are you using?

**Comment by xjy12345654** [comment]
> @xjy12345654
> 你用的是哪个版本？
> what version are you using?

大佬啊 用的就是示例中的版本  应该是最新的  windows系统  jdk11   而且要修改package.json中的东西   
"devDependencies": {
    "@es4x/create": "0.13.3",
    "@es4x/unit": "3.9.4"
  }
 但是到 npm 启动时候 就失败了........
> 
![20201208095752](https://user-images.githubusercontent.com/38834664/101428703-3716e380-393c-11eb-8237-a6136195a74c.png)

**Comment by xjy12345654** [comment]
@fantasy0v0  大佬我用的 就是示例中的 应该是最新版吧   创建中还有其他错误  要修改 package.json  
"devDependencies": {
    "@es4x/create": "0.13.3",
    "@es4x/unit": "3.9.4"
  }
但是到最后一步 npm start  就开始失败报错了.......

**Comment by xjy12345654** [comment]
@fantasy0v0    按照示例  到 npm install时候  

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@vertx%2fcreate - Not found
npm ERR! 404
npm ERR! 404  '@vertx/create@0.13.3' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'myproject'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

然后我修改了 "@vertx/create": "0.13.3",  为 "@es4x/create": "0.13.3"

![20201208103403](https://user-images.githubusercontent.com/38834664/101430930-eeadf480-3940-11eb-9931-744360fff4cb.png)

**Comment by fantasy0v0** [comment]
@xjy12345654 我在我自己电脑上试了是可以正常启动的，但我的环境跟你的不一样，可能是Windows下特有的问题，有空我在Windows下试试。

**Comment by xjy12345654** [comment]
@fantasy0v0  好  无意中发现的这个框架，不行的话只能玩 fastify ......或者直接学 rust  搞  Rust web框架

**Comment by chengenzhao** [comment]
0.14.0要发了，用最新的版本吧
现在es4x还不是很稳定，毕竟连1.0都还没上

**Comment by pmlopes** [comment]
@fantasy0v0 for the `@vertx/create` you can manually download the 0.14.0 from github releases: https://github.com/reactiverse/es4x/releases/tag/0.14.0

**Comment by pmlopes** [comment]
All bits of the 0.14.0 are being pushed to the mirrors ATM. So they should be soon on npm and maven

**Comment by xjy12345654** [comment]
@pmlopes  @chengenzhao  @fantasy0v0   Thank you, everyone has started normally according to the example! Update to 0.14 and it is normal.
