### ISSUE TITLE
i found some errors in 0.14.0-CR1

### ISSUE THREAD

**Issue by fantasy0v0** [reactiverse/es4x#464]
my version:
VM:        OpenJDK 64-Bit Server VM - 14.0.2
VM Vendor: null
Vert.x:    4.0.0.CR1
ES4X:      0.14.0-CR1
graaljs:   20.2.0

1. package.json has extra characters

![image](https://user-images.githubusercontent.com/9549027/100984096-35889c80-3585-11eb-8006-8ce885181faf.png)

This problem is caused by com.github.cliftonlabs.json_simple.Jsoner#prettyPrint
https://github.com/reactiverse/es4x/blob/d51190a6d3747397970ab814c36d38dc9e64b5d1/pm/src/main/java/io/reactiverse/es4x/commands/JSON.java#L39
```java
System.out.println(Jsoner.prettyPrint("{\"@es4x/create\"}"));
```
will print 
```json
{
	"@es4x\/create"
}
```

2. wrong version number 

version of @vertx/core is 4.0.0-CR1 not 4.0.0.CR1

3. Module '"./enums"' has no exported member 'TracingPolicy'.

node_modules/@vertx/core/options.d.ts:1767:10 - error TS2305:

**Comment by pmlopes** [comment]
Thanks for the report @fantasy0v0 I've just pushed to `develop` a fix to avoid relying on `simple-json`. so the generated json is correct now.

I've to figure out why the `TracingPolicy` is missing.

**Comment by pmlopes** [comment]
Following up here: https://github.com/eclipse-vertx/vert.x/pull/3683

**Comment by pmlopes** [comment]
The json bug is also fixed!

**Comment by pmlopes** [comment]
@fantasy0v0 I've prepared a new release `0.14.0` currently if you're testing using maven you can verify the artifacts if you use the following statging maven repo:

https://oss.sonatype.org/content/repositories/ioreactiverse-1147/

**Comment by pmlopes** [comment]
0.14.0 is being pushed to mirrors, all bits on maven and npm.
