### ISSUE TITLE
Missing @es4x/create 0.14.0

### ISSUE THREAD

**Issue by UglyHobbitFeet** [reactiverse/es4x#469]
The latest package I see via npm is for @es4x/create v0.13.3  when doing a typical npm install/update

Looking at the following URL, I can see it's there but in the versions tab it's not tagged as latest
https://www.npmjs.com/package/@es4x/create/v/0.14.0

**Comment by pmlopes** [comment]
the tag has been updated! :+1:

**Comment by UglyHobbitFeet** [comment]
Got it, thanks!
