### ISSUE TITLE
Anyway to start vertx using -Xmx to limit ram allocating 

### ISSUE THREAD

**Issue by xinxilas** [reactiverse/es4x#480]
Hello friend,

Is there anyway to configure ES4x to start vertx using -Xmx on my Graalvm to limit ram allocating ?

I pretend to run es4x tests on  aws ec2 t2.micro

**Comment by pmlopes** [comment]
@xinxilas Have you tried to set the variable `JAVA_OPTS`?

If you use the launcher scripts they should take that environment variable in consideration I think.

If not, let me know how you're running the application!
