### ISSUE TITLE
TypeScript example does not build

### ISSUE THREAD

**Issue by outloudvi** [reactiverse/es4x#521]
I was once able to build my es4x TypeScript application and pack it into a Docker image. However, my recent attempt to build the Docker images with latest documentation does not work. It seems that even the [example TypeScript code](https://github.com/reactiverse/es4x/tree/develop/examples/typescript) does not build for me currently:

```
> empty-project@1.0.0 prestart /tmp/v/es4x/examples/typescript
> tsc

index.ts:1:23 - error TS2688: Cannot find type definition file for 'es4x'.

1 /// <reference types="es4x" />
                        ~~~~


Found 1 error.

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! empty-project@1.0.0 prestart: `tsc`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the empty-project@1.0.0 prestart script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-04-19T09_10_53_837Z-debug.log
```

Version detail:
```
# node -v
v14.16.1
# npm -v
6.14.12
# java --version
openjdk 13.0.4 2020-07-14
OpenJDK Runtime Environment (build 13.0.4+8-Ubuntu-120.04)
OpenJDK 64-Bit Server VM (build 13.0.4+8-Ubuntu-120.04, mixed mode)
```

**Comment by pmlopes** [comment]
@outloudvi sorry about that this has been fixed with:

https://github.com/reactiverse/es4x/commit/9f6ddfc6cc9c193a31e281d383d43cf5042b22e0

The new base reference is "@vertx/core" to avoid having to mess up with npm, plus the example was using an old version of the package management tools.
