### ISSUE TITLE
@vertx/web-validation missing api types

### ISSUE THREAD

**Issue by BeneStem** [reactiverse/es4x#537]
Hey there, it seems that `@vertx/web-validation` is missing important types of its api...

<img width="934" alt="image" src="https://user-images.githubusercontent.com/2619581/120922527-07b61900-c6ca-11eb-8dee-8934293baa22.png">

The equivalent java imports would be:

```java
import io.vertx.ext.web.validation.builder.*;
import io.vertx.ext.web.validation.builder.Bodies;
import io.vertx.ext.web.validation.builder.Parameters;
```

Or am I missing something?

Best,
/ben

**Comment by pmlopes** [comment]
This is the fallback generation when the codegen plugin cannot find the right data. I need to verify upstream what is blocking it from being generated!

Thanks!

**Comment by pmlopes** [comment]
Yes, this is an upstream issue that needs to be addressed:

https://github.com/vert-x3/vertx-web/blob/master/vertx-web-validation/src/main/java/io/vertx/ext/web/validation/builder/ValidationHandlerBuilder.java

Doesn't properly annotate the class so the codegen plugin cannot know the types and assumes `any`.

**Comment by BeneStem** [comment]
Thank you very much for the fast reply!

**Comment by pmlopes** [comment]
I've added the missing annotations upstream. There are still many "genignore" which means that in many places we will have "any", once this gets published I'll run the tsc checks and try to add more details from there.

**Comment by BeneStem** [comment]
Great, thank you!

**Comment by BeneStem** [comment]
@pmlopes Its not released on npm yet, right?

**Comment by pmlopes** [comment]
Hi, no, not yet. The upstream changes are merged on the upcoming 4.2.0 release of vert.x once we have a upstream release I'll build the es4x packages.

**Comment by BeneStem** [comment]
thanks!

**Comment by BeneStem** [comment]
@pmlopes is it possible that the Binding for the `io.vertx.json.schema.draft7.dsl.Schemas` class is still missing?

I can't call objectSchema() or intSchema() and so on...
