### ISSUE TITLE
GraalVM intl-402 support

### ISSUE THREAD

**Issue by vh1572** [reactiverse/es4x#552]
Hi,

I'm using es4x for a project which requires the GraalVM intl-402 support to be enabled.

There is no way to configure it easily. The only way I managed to configure it was setting the environment variable before starting the application:
export JAVA_TOOL_OPTIONS=-Dpolyglot.js.intl-402=true

Would it be possible to include it by default in the es4x-cli.js or to make it configurable by some command line argument?

Thanks

**Comment by pmlopes** [comment]
@vh1572 did you try:

If you're using npm:

```
npm start -- -Dpolyglot.js.intl-402=true
```

Or using the generated launchers:

```
./node_modules/.bin/es4x -Dpolyglot.js.intl-402=true main.js
```

**Comment by pmlopes** [comment]
I did a small test and can assert that this works:

```js
print(process.properties['polyglot.js.intl-402'])

print(Intl.NumberFormat)
```

**Comment by vh1572** [comment]
Hi, yes, I can also confirm that the version es4x -Dpolyglot.js.intl-402=true works.

Thank you.
