### ISSUE TITLE
Additional jar libs in classpath

### ISSUE THREAD

**Issue by vh1572** [reactiverse/es4x#553]
Hi,

I'm using ES4X with vertx hazelcast cluster in an application, but under kubernetes.
Unfortunately, the vertx hazelcast library comes without the classes required for kubernetes.

Is there a way to include additional jar files into the classpath?

For the moment, I'm overwriting the hazelcast.jar with hazelcast-all.jar in the node-modules folder when building the docker image, but this is an ugly solution. I'll also ask the vertx team if they could use in the library the hazelcast-all by default.

Thank you,
Csaba Vajda

**Comment by pmlopes** [comment]
@vh1572 yes you can:

in your `package.json` add an array named `mvnDependencies` in `GAV` format , for example:

```json
{
  "mvnDependencies" : [
    "com.hazelcast:hazelcast-kubernetes:2.2.3" 
  ]
}
```

You can use this to force specific versions during the resolution, you can't however, exclude dependencies

**Comment by vh1572** [comment]
Yes, that works, thank you.
