### ISSUE TITLE
Missing bin/es4x-launcher.jar in Hello World example

### ISSUE THREAD

**Issue by tpfau** [reactiverse/es4x#575]
Hi, 
I just wanted to start a new es4x project as indicated in the Hello World example page (here)[https://reactiverse.io/es4x/get-started/hello-world.html#create-a-new-project].   
When Calling `es4x project` I'm getting a "Missing bin/es4x-launcher.jar" message, which I don't really understand. Is this intentional? I noticed the same happened in #545, and it also showed up in the example given by @pmlopes. Actually, when I run it as indicated in the reply, I get an error from npm :
```
$ npm init @es4x project
Missing bin/es4x-launcher.jar
npm ERR! code 3
npm ERR! path ~/my-app
npm ERR! command failed
npm ERR! command sh -c es4x "project"
```
which indicates that this missing message is indeed an error.
Am I doing something wrong? Or is this intentional? It's just a very odd message coming up. Seems not to stop development, but maybe it should still be fixed?

**Comment by pmlopes** [comment]
@tpfau this is a non-desired side effect. During the init some validation is run by the launch script which should not be the case. For now, it can be safely ignored, and will go away once a `npm install` is run.

**Comment by pmlopes** [comment]
On `develop` i've replaced the error with just a message to run the install action. Once vertx releases 4.2.5, i'll build an official release and tag this issue on it.
