### ISSUE TITLE
Problem using await

### ISSUE THREAD

**Issue by tpfau** [reactiverse/es4x#585]
Hi,
I'm currently having a problem (likely me not understanding Javascript again) with the `await` keyword in es4x code. 
If I take the example from [here](https://reactiverse.io/es4x/advanced/vertx.html#async-await):
```
try {
  let server = await vertx
    .createHttpServer()
    .listen(0);

  console.log('Server Ready!');
} catch (err) {
  console.log('Server startup failed!')
}
```
and simply put this into my index.js and try to run it with es4x index.js, it fails with:
```
Failed in deploying verticle caused by SyntaxError: /home/thomas/Work/TestJs2/index.js:5:21 Expected ; but found vertx
  let server = await vertx
```
As I said, likely me screwing up javascript again, but a hint would be great.

**Comment by pmlopes** [comment]
Hi @tpfau I believe the issue is that you're trying to use `await` outside an `async` function.

If you would wrap your script as:

```js
(async function futureTest1 () {
  let server = await vertx
      .createHttpServer()
      .requestHandler(req => {
      })
      .listen(0);

  console.log('Server Ready!');
})();
```

I think it would work. The error message is comming from graal and indeed is not very descriptive

**Comment by tpfau** [comment]
Thanks,
That was indeed the issue.
Might be good to put the example in an async function then. 
Should I just put in a PR with your suggestion as an update for the docs?

**Comment by pmlopes** [comment]
Please do! Thanks!
