### ISSUE TITLE
[Question] How to build a file for java graaljs?

### ISSUE THREAD

**Issue by aitimate** [reactiverse/es4x#599]
## I'm new at this....

![image](https://user-images.githubusercontent.com/47878132/210654453-9d59f40c-3cf3-4c94-b988-c29ab6b74b75.png)

![image](https://user-images.githubusercontent.com/47878132/210654776-e275bbcd-a661-4516-b3d6-0fd3c5f6a686.png)

**Comment by pmlopes** [comment]
Currently there is no `pack` support, however I think it could be done using a variation of the dockerfile command. Using this command we generate a general purpose dockerfile, instead we could generate a tar/zip file along side with the one by npm, but extending it with all the required stuff to run on a jvm/graalvm, excluding the jvm/graalvm itself.
