### ISSUE TITLE
Release Vertx 4.4.0 npm modules

### ISSUE THREAD

**Issue by bkoripalli** [reactiverse/es4x#602]

**Comment by bkoripalli** [comment]
@pmlopes  without es4x release, is it possible to release vertx libraries available as npm modules?

**Comment by pmlopes** [comment]
https://github.com/reactiverse/es4x/releases/tag/0.20.0

**Comment by pmlopes** [comment]
The bump is still on Graal 22 because there are regressions related to module resolution with 23
