### ISSUE TITLE
docker file should run npm update instead install during 1st step

### ISSUE THREAD

**Issue by pmlopes** [reactiverse/es4x#89]

**Comment by pmlopes** [comment]
see: https://nodejs.org/en/docs/guides/nodejs-docker-webapp/

**Comment by sdnetwork** [comment]
Fix by https://github.com/reactiverse/es4x/pull/88 (https://github.com/reactiverse/es4x/pull/88/commits/a78ff0e170cc3a43428305eaf57f9e59d3696b3b)
